/**
 * Textos de la interfaz en español e inglés. t(clave) devuelve el texto del idioma activo.
 */

/** Diccionario de traducciones por idioma. */
const TRANSLATIONS = { es: { classic: 'Clásicos', platform: 'Plataforma', stats: 'Estadísticas', add: '+ Añadir', search: 'Buscar nivel…', unplaced: 'Sin colocar', pending: 'Aún no ubicado', notin: 'No está en lista', name: 'Nombre', lid: 'ID del nivel', creator: 'Creador (publisher)', diff: 'Dificultad', pos: 'Posición en mi top', attC: 'Intentos en copia', attN: 'Intentos en normal', attT: 'Intentos totales', tN: 'Tiempo normal', tP: 'Tiempo práctica', tPC: 'Tiempo práctica copia', tT: 'Tiempo total', date: 'Fecha de completado', link: 'Video (YouTube)', enj: 'Disfrutabilidad', lik: 'Nivel de agrado', tags: 'Tags', notes: 'Notas', deaths: 'Muertes por porcentaje (ej: 63% x4)', best: 'Mejor % antes de pasarlo', save: 'Guardar', del: 'Eliminar', edit: 'Editar', close: 'Cerrar', lv: 'Niveles', hrs: 'Horas', avg: 'Intentos por nivel', most: 'Más intentos', byD: 'Por dificultad', byY: 'Completados por año', tl: 'Cronograma (intentos por nivel)', ok: 'Coincidencias con AREDL', kind: 'Lista', confirm: '¿Eliminar este nivel?', empty: 'Sin niveles. Pulsa «Añadir».', dh: 'Muertes por porcentaje', creators: 'Colaboradores (separados por coma)', found: '✓ Encontrado en la lista', nf: '⚠ No se encontró en la lista; escribe el ID a mano', nolist: '⚠ Ese ID no está en la lista (normal si no es de AREDL/AREPL)', nocache: 'Pulsa ⟳ AREDL para poder validar el nivel', nothumb: '⚠ Sin miniatura para ese ID', dU: 'muertes', att: 'intentos', tagsT: 'Gestionar tags', by: 'por', ap: 'Posición en la AREDL', onl: 'En la lista', s1: 'Información del nivel', s2: 'Posiciones', s3: 'Intentos y tiempo', s4: 'Completado', s5: 'Valoración', s6: 'Notas y muertes', newTag: 'Nuevo tag', confirmTag: '¿Quitar este tag de todos los niveles?' },
    en: { classic: 'Classic', platform: 'Platformer', stats: 'Statistics', add: '+ Add', search: 'Search level…', unplaced: 'Unplaced', pending: 'Not placed yet', notin: 'Not on list', name: 'Name', lid: 'Level ID', creator: 'Creator (publisher)', diff: 'Difficulty', pos: 'Position in my top', attC: 'Copy attempts', attN: 'Normal attempts', attT: 'Total attempts', tN: 'Normal time', tP: 'Practice time', tPC: 'Copy practice time', tT: 'Total time', date: 'Completion date', link: 'Video (YouTube)', enj: 'Enjoyment', lik: 'Level appeal', tags: 'Tags', notes: 'Notes', deaths: 'Deaths per percent (e.g. 63% x4)', best: 'Best % before beating it', save: 'Save', del: 'Delete', edit: 'Edit', close: 'Close', lv: 'Levels', hrs: 'Hours', avg: 'Attempts per level', most: 'Most attempts', byD: 'By difficulty', byY: 'Completed per year', tl: 'Timeline (attempts per level)', ok: 'AREDL matches', kind: 'List', confirm: 'Delete this level?', empty: 'No levels. Press “Add”.', dh: 'Deaths per percent', creators: 'Collaborators (comma separated)', found: '✓ Found in the list', nf: '⚠ Not found in the list; type the ID by hand', nolist: '⚠ That ID is not in the list (normal if not AREDL/AREPL)', nocache: 'Press ⟳ AREDL to enable validation', nothumb: '⚠ No thumbnail for that ID', dU: 'deaths', att: 'attempts', tagsT: 'Manage tags', by: 'by', ap: 'AREDL position', onl: 'On the list', s1: 'Level info', s2: 'Rankings', s3: 'Attempts & time', s4: 'Completion', s5: 'Rating', s6: 'Notes & deaths', newTag: 'New tag', confirmTag: 'Remove this tag from all levels?' } };
Object.assign(TRANSLATIONS.es, {
    didYouMean: '¿Quisiste decir:', wish: 'Wishlists', st_todo: 'Sin empezar', st_prog: 'En progreso', st_done: 'Completado', first: 'Primeros pasos', prof: 'Perfil', pnew: 'Nuevo perfil', pname: 'Nombre del perfil', pdel: '¿Eliminar este perfil y todos sus datos?', pdel2: 'Eliminar perfil', opt: 'Opciones', bell: 'Notificaciones', nonot: 'Todo en orden ✓', aUnp: 'Sin colocar', aWish: 'Completado en wishlist, falta añadirlo a tu lista', aNoId: 'Niveles sin ID (sin miniatura)', wnew: '+ Nueva wishlist', wren: 'Renombrar', wdelL: 'Eliminar lista', wname: 'Nombre de la wishlist', witem: '+ Añadir nivel', toC: '→ Clásicos', toP: '→ Plataforma', added: '✓ En tu lista', addedOk: 'Añadido a «Sin colocar»', back: '← Volver', tgs: 'Buscar tag…', sa: 'Intentos', sT: 'Tiempo de juego', sh: 'Tags y notas', wconf: '¿Eliminar?', noWL: 'Aún no hay wishlists' });
Object.assign(TRANSLATIONS.en, {
    didYouMean: 'Did you mean:', wish: 'Wishlists', st_todo: 'Not started', st_prog: 'In progress', st_done: 'Completed', first: 'First steps', prof: 'Profile', pnew: 'New profile', pname: 'Profile name', pdel: 'Delete this profile and all its data?', pdel2: 'Delete profile', opt: 'Options', bell: 'Notifications', nonot: 'All good ✓', aUnp: 'Unplaced', aWish: 'Completed in wishlist, not yet added to your list', aNoId: 'Levels without ID (no thumbnail)', wnew: '+ New wishlist', wren: 'Rename', wdelL: 'Delete list', wname: 'Wishlist name', witem: '+ Add level', toC: '→ Classic', toP: '→ Platformer', added: '✓ In your list', addedOk: 'Added to “Unplaced”', back: '← Back', tgs: 'Search tag…', sa: 'Attempts', sT: 'Play time', sh: 'Tags & notes', wconf: 'Delete?', noWL: 'No wishlists yet' });
Object.assign(TRANSLATIONS.es, { home: 'Inicio', lists: 'Mis listas', statsSub: 'Resumen y cronograma', exists: 'Ese nivel ya está en esa lista' });
Object.assign(TRANSLATIONS.en, { home: 'Home', lists: 'My lists', statsSub: 'Summary & timeline', exists: 'That level is already in that list' });
Object.assign(TRANSLATIONS.es, { rights: 'Todos los derechos reservados', terms: 'Términos de uso', privacy: 'Privacidad', credits: 'Créditos', termsTxt: 'Personal Ranked Progress es un proyecto personal para llevar el seguimiento de niveles de Geometry Dash. Se ofrece «tal cual», sin garantías de ningún tipo.\n\nEl código, el diseño y el contenido original son obra de su autor y están protegidos por derechos de autor: no pueden copiarse ni redistribuirse sin permiso.\n\nEste proyecto no está afiliado a RobTop Games, a Geometry Dash ni a la AREDL.', privacyTxt: 'Esta aplicación no usa cuentas ni servidores propios. Tus datos (niveles, perfiles y wishlists) se guardan solo en el almacenamiento local de tu navegador y únicamente salen de él si exportas un perfil.\n\nPara mostrar información se consultan servicios externos: la API de la AREDL (posiciones y publishers), Level Thumbnails (miniaturas de niveles) y YouTube (miniaturas de video). No se usan cookies de seguimiento ni analítica.', creditsTxt: 'Posiciones y publishers: All Rated Extreme Demons List (aredl.net).\nMiniaturas de niveles: Level Thumbnails (levelthumbs.prevter.me).\nGeometry Dash © RobTop Games. Las marcas pertenecen a sus respectivos dueños.', cancel: 'Cancelar', ok2: 'Aceptar', pick: 'Selecciona un nivel de la lista para ver su información', syncL: 'Actualizar desde AREDL', back2: 'Volver', profs: 'Perfiles', active: 'Activo', lastP: 'Debe quedar al menos un perfil', data: 'Datos', impP: 'Importar perfil', expP: 'Exportar perfil' });
Object.assign(TRANSLATIONS.en, { rights: 'All rights reserved', terms: 'Terms of use', privacy: 'Privacy', credits: 'Credits', termsTxt: 'Personal Ranked Progress is a personal project for tracking Geometry Dash levels. It is provided "as is", without warranties of any kind.\n\nThe code, design and original content are the work of their author and are protected by copyright: they may not be copied or redistributed without permission.\n\nThis project is not affiliated with RobTop Games, Geometry Dash or the AREDL.', privacyTxt: 'This app uses no accounts and no servers of its own. Your data (levels, profiles and wishlists) is stored only in your browser\'s local storage and leaves it only if you export a profile.\n\nExternal services are queried to display information: the AREDL API (positions and publishers), Level Thumbnails (level thumbnails) and YouTube (video thumbnails). No tracking cookies or analytics are used.', creditsTxt: 'Positions and publishers: All Rated Extreme Demons List (aredl.net).\nLevel thumbnails: Level Thumbnails (levelthumbs.prevter.me).\nGeometry Dash © RobTop Games. Trademarks belong to their respective owners.', cancel: 'Cancel', ok2: 'OK', pick: 'Select a level from the list to see its details', syncL: 'Update from AREDL', back2: 'Back', profs: 'Profiles', active: 'Active', lastP: 'At least one profile is required', data: 'Data', impP: 'Import profile', expP: 'Export profile' });

/** Traduce una clave al idioma activo. */
const t = k => TRANSLATIONS[ui.lang][k] ?? k;
